name: Maven Build

on:
  push:
    branches:
      - main  # O el nombre de la rama que prefieras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
