name: Maven Build

on:
  push:
    branches:
      - main  # O el nombre de la rama que prefieras

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
    
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
      
    - run: mvn -B package --file pom.xml
